Add workflow step to push Dozer image to Dockerhub
getdozer/dozer pull request #1537
Opened 2023-05-05 14:59 UTC by abhishekmishragithub

Add the docker hub push workflow step in `release.yaml` workflow file. 

**Note:**
   - Add `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` as a secret to the repo settings.
   - Added a condition to push to docker hub only when there is a release.

2023-05-11 08:53 UTC, mediuminvader requested changes

2023-05-11 08:53 UTC, mediuminvader commented on .github/workflows/release.yaml
> +
Execute thin only when ubuntu x86 release is running

2023-05-11 10:55 UTC, mediuminvader approved these changes

2023-05-11 12:18 UTC, abhishekmishragithub commented
This has been tested across `release-dev` branch to trigger the workflow.
- Here is the workflow log: https://github.com/getdozer/dozer/actions/runs/4945443681/jobs/8842178444
- You can cross-check the `containerimage.digest` value with pushes images on Docker hub 
- Screenshot from Docker hub

![image](https://github.com/getdozer/dozer/assets/38150419/adb277a3-1e56-4c9f-be52-9abf42eda969)

2023-05-11 12:19 UTC, chubei commented
macos workflow failed?

2023-05-11 12:34 UTC, abhishekmishragithub commented
> macos workflow failed?

Yeah, but I am unable to debug why, also we needed to do docker push only when `if: matrix.os == 'ubuntu-20-16-cores'`
it should skip for macos if that's the case.

2023-09-27 08:32 UTC, chubei commented
Included in #1558

2023-09-27 08:32 UTC, closed without merging