feat: udf onnx config placeholder
getdozer/dozer pull request #1831
Opened 2023-08-08 04:25 UTC by chloeminkyung

```yaml
udfs:
   config: !Onnx
     path: ./models/mode_file 
   name: is_fraudolent
```

2023-08-09 06:43 UTC, chubei requested changes

2023-08-09 06:43 UTC, chubei commented on dozer-types/src/models/config.rs
> +    pub udf: Option<UdfConfig>,
`udfs: Vec<UdfConfig>`

2023-08-09 06:43 UTC, chubei commented on dozer-types/src/models/udf_config.rs
> +    #[serde(default = "default_udf_type")]
We shouldn't `default` this field

2023-08-09 06:43 UTC, chubei commented on dozer-types/src/models/udf_config.rs
> +fn default_udf_type() -> Option<UdfType> {
`OnnxConfig::default` doesn't make sense

2023-08-10 04:22 UTC, chloeminkyung commented on dozer-types/src/models/config.rs
> +    pub udf: Option<UdfConfig>,
addressed

2023-08-10 04:22 UTC, chloeminkyung commented on dozer-types/src/models/udf_config.rs
> +    #[serde(default = "default_udf_type")]
addressed

2023-08-10 04:22 UTC, chloeminkyung commented on dozer-types/src/models/udf_config.rs
> +fn default_udf_type() -> Option<UdfType> {
addressed

2023-08-10 04:22 UTC, chloeminkyung commented on dozer-types/src/models/udf_config.rs
> +fn default_udf_type() -> Option<UdfType> {
addressed

2023-08-10 04:46 UTC, chubei approved these changes

2023-08-10 05:24 UTC, merged