chore: Create unit tests workflow
getdozer/dozer pull request #1910
Opened 2023-08-24 13:25 UTC by mediuminvader

2023-08-24 13:28 UTC, chubei requested changes

2023-08-24 13:28 UTC, chubei commented on .github/workflows/unit.yaml
> +name: Dozer Coverage
We need to change the name. It's shown in "Actions" tab on Github

2023-08-24 13:28 UTC, chubei commented on .github/workflows/unit.yaml
> +  # pull_request_target:
I thought we're going to run on PRs?

2023-08-24 13:28 UTC, chubei commented on .github/workflows/unit.yaml
> +      - name: Install stable with llvm-tools-preview
We don't need llvm-tools-preview

2023-08-24 13:41 UTC, mediuminvader commented on .github/workflows/unit.yaml
> +  # pull_request_target:
I want to test manually first

2023-08-24 13:45 UTC, chubei commented on .github/workflows/unit.yaml
> +          LLVM_PROFILE_FILE: "cargo-test-%p-%m.profraw"
We don't want these env vars.

2023-08-24 13:45 UTC, chubei commented on .github/workflows/unit.yaml
> +          LLVM_PROFILE_FILE: "cargo-test-%p-%m.profraw"
We don't want these env vars

2023-08-24 14:03 UTC, chubei approved these changes

2023-08-31 02:50 UTC, chubei requested changes

2023-08-31 02:50 UTC, chubei commented on .github/workflows/coverage.yaml
> +      - "v*.*.*"
If we run it on merge group, don't need to run again on push

2023-08-31 02:50 UTC, chubei commented on .github/workflows/unit.yaml
> +  merge_group:
coverage runs on merge group, so unit doesn't need to run on merge group

2023-08-31 07:46 UTC, merged